#TODO: Add Code to handle v9 and v10 nightly builds, once it is added to the tool
jobs:
- job: Linux_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 0.10:
        NODE_VERSION: '0.10'
      Node 0.12:
        NODE_VERSION: '0.12'
      Node 1.8:
        NODE_VERSION: '1.8'
      Node 2.5:
        NODE_VERSION: '2.5'
      Node 3.3:
        NODE_VERSION: '3.3'
      Node 4.9:
        NODE_VERSION: '4.9'
      Node 5.12:
        NODE_VERSION: '5.12'
      Node 6.14:
        NODE_VERSION: '6.14'
      Node 7.10:
        NODE_VERSION: '7.10'
      Node 8.12:
        NODE_VERSION: '8.12'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - template: "azure-pipelines-steps.yml"
    parameters:
      NODE_VERSION: $(NODE_VERSION)

- job: Linux_CanFail
  dependsOn: Linux_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 9.x:
        NODE_VERSION: '9.x'
      Node 10.x:
        NODE_VERSION: '10.x'
  continueOnError: true
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - template: "azure-pipelines-steps.yml"
    parameters:
      NODE_VERSION: $(NODE_VERSION)


- job: Windows_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 0.10:
        NODE_VERSION: '0.10.'
      Node 0.12:
        NODE_VERSION: '0.12'
      Node 1.8:
        NODE_VERSION: '1.8'
      Node 2.5:
        NODE_VERSION: '2.5'
      Node 3.3:
        NODE_VERSION: '3.3'
      Node 4.9:
        NODE_VERSION: '4.9'
      Node 5.12:
        NODE_VERSION: '5.12'
      Node 6.14:
        NODE_VERSION: '6.14'
      Node 7.10:
        NODE_VERSION: '7.10'
      Node 8.12:
        NODE_VERSION: '8.12'
  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: "azure-pipelines-steps.yml"
    parameters:
      NODE_VERSION: $(NODE_VERSION)